# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3b09d1ddaaffacc81e06e24c1e8dfaab01141063c0eca132404e1793ecf6f41ef13090b347cdebb1cb5f52f220c540eedfd64919929edba77fb677f8cb799b2

test:
  secret_key_base: daca8555dc92105cf72a3611dc79e13df4fb4eb737806375115d3d70ed0e11243a827b1e554e70fa78a09a2224d19149875f92f1933e41c8b294e61641de29c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
